### ISSUE TITLE
Server is down

### ISSUE THREAD

**Issue by BBlackwo** [BlockchainCommons/spotbit#103]
Hi :wave:, first off I love the idea of this project!

I am trying to use [spotbit over tor](http://h6zwwkcivy2hjys6xpinlnz2f74dsmvltzsd4xb42vinhlcaoe7fdeqd.onion) to get the AUD price in specter-desktop and it isn't working as the onion service is down. I noticed https://spotbit.io is down too. 

Are there plans to get the servers up and running again? Or does it need to be self hosted from now on?

**Comment by nochiel** [comment]
> I am trying to use [spotbit over tor](http://h6zwwkcivy2hjys6xpinlnz2f74dsmvltzsd4xb42vinhlcaoe7fdeqd.onion) to get the AUD price in specter-desktop and it isn't working as the onion service is down. I noticed https://spotbit.io is down too.
> 
> Are there plans to get the servers up and running again? Or does it need to be self hosted from now on?

I need to update the documentation. Please use the following endpoints:

- <http://r5sru63gzyrnaayaua2ydo32f4hf6vd33bq6qmtktx3wjoib2cwi2gqd.onion>
- <https://spotbit.info>
- <https://spotbit.info/docs>

**Comment by BBlackwo** [comment]
Great thank you. Don't forget the repo website link too 🙂
![Screenshot_20230829-213058~2](https://github.com/BlockchainCommons/spotbit/assets/7598058/4cbe2966-6735-451d-bc27-9c4a7d6624b7)

**Comment by nochiel** [comment]
> Great thank you. Don't forget the repo website link too 🙂 

Thanks for pointing that out as well. I've now corrected the link.

**Comment by BBlackwo** [comment]
Hi @nochiel, It looks like the server is down again :sweat_smile: I'm getting a `502 Bad Gateway` from clearnet and tor.

**Comment by nochiel** [comment]
> Hi @nochiel, It looks like the server is down again :sweat_smile: I'm getting a `502 Bad Gateway` from clearnet and tor.

I'm looking into it.

**Comment by nochiel** [comment]
Re #105. Exchange APIs seem to have changed in a way that breaks Spotbit and we need to update Spotbit to handle the changes.
