### ISSUE TITLE
Adding Spotbit to our BDK users webpage

### ISSUE THREAD

**Issue by thunderbiscuit** [BlockchainCommons/spotbit#107]
Hi there! I'm thunderbiscuit, I work on the core BDK team (mostly on language bindings, including the Python ones). We're building a page on our website that includes projects that use BDK, and I'm reaching out to know if you'd be ok with us adding you there! You can take a look at the page on our website here: https://bitcoindevkit.org/case-studies/

Thank you!

**Comment by shannona** [comment]
Sorry for the delay. Yes, we'd be delighted to be referenced. 

We also use BDK in our mori-cli, though I'm not sure how functional it is as it's an Alpha:
https://github.com/BlockchainCommons/mori-cli

**Comment by thunderbiscuit** [comment]
Awesome! You're now on the page: https://bitcoindevkit.org/case-studies/. If you ever want to change the tagline or the logo give me a shout!
