### ISSUE TITLE
UTC time getting stuck

### ISSUE THREAD

**Issue by Fonta1n3** [BlockchainCommons/spotbit#13]
I am continually testing this endpoint: 
`http://kxw4ekzovnar64qylfryczn55ftroachfeqvwjsxl5rnykouzz33kvid.onion/now/usd/coinbase`

First of all the UTC time is off by a couple of hours (this was made at 3:00am UTC but showing 5:31am)
`{"close":11719.995,"currency_pair":"BTC-USD","datetime":"2020-08-20 05:31:50","high":0.0,"id":209,"low":0.0,"open":0.0,"timestamp":1597901510,"vol":0.0}`

Making the same request about 30 minutes later returns the same `"datetime":"2020-08-20 05:31:50"`.

**Comment by nochiel** [comment]
Fixed by master. Now Spotbit sets the timezone. This should result in consistent timestamps.
