### ISSUE TITLE
Coinbase rate is off

### ISSUE THREAD

**Issue by Fonta1n3** [BlockchainCommons/spotbit#14]
Making a call directly to the Coinbase api `https://api.coinbase.com/v2/prices/btc-usd/buy` returns: `{"data":{"base":"BTC","currency":"USD","amount":"11851.63"}}`. Using `https://api.coinbase.com/v2/prices/btc-usd/sell` also does not return similar price.

However making a call to Spotbit at the same time with `http://kxw4ekzovnar64qylfryczn55ftroachfeqvwjsxl5rnykouzz33kvid.onion/now/usd/coinbase`returns:
```
{"close":11719.995,"currency_pair":"BTC-USD","datetime":"2020-08-20 05:31:50","high":0.0,"id":209,"low":0.0,"open":0.0,"timestamp":1597901510,"vol":0.0}
```

It seems more likely that Spotbit is getting stuck.

**Comment by watersnake1** [comment]
> I tried messing around with `keepWeeks`, setting to 0 and 1, same result. Removing it caused a crash.

Just fixed and pushed this issue. Was just a lack of proper error checking.

**Comment by Fonta1n3** [comment]
@watersnake1 where was it pushed to? The last commit in `development_signed` was two days ago.

**Comment by watersnake1** [comment]
Sorry I forgot to push. It went to `development-signed`.

**Comment by nochiel** [comment]
Fixed in master.
