### ISSUE TITLE
Intermittently becoming unresponsive

### ISSUE THREAD

**Issue by Fonta1n3** [BlockchainCommons/spotbit#15]
Spotbit generally becomes unresponsive, to test simply continually query an endpoint throughout the day such as `http://kxw4ekzovnar64qylfryczn55ftroachfeqvwjsxl5rnykouzz33kvid.onion/now/usd/coinbase`. 

I was using Spotbit on the same VPS which was running other Tor hidden services, those HS were responding fine even when Spotbit was stuck so that rules out that it is a Tor issue. Interestingly when Spotbit becomes responsive again it shows outdated data and is stuck on the same time as per #13

**Comment by nochiel** [comment]
Fixed in master.
