### ISSUE TITLE
Create a website for Spotbit.info

### ISSUE THREAD

**Issue by watersnake1** [BlockchainCommons/spotbit#20]
Spotbit.info currently redirects to the project github page. While issue #19 refers to accessing spotbit.info via a tor enabled browser, for normal browsers Spotbit should have a website.

The website should include documentation for spotbit, a list of available servers, a link to spotbit's github and twitter, and a logo.

**Comment by nochiel** [comment]
<spotbit.info> has a frontend that is a work-in-progress.
