### ISSUE TITLE
Source Directory Missing

### ISSUE THREAD

**Issue by shannona** [BlockchainCommons/spotbit#25]
The source code directory mentioned in the README is currently missing:

/home/spotbit/source

This means that the logfile is also missing:

/home/spotbit/source/spotbit.log

```
$ sudo ls -lagh ~spotbit
total 36K
drwxr-xr-x 5 sudo 4.0K Sep 22 12:53 .
drwxr-xr-x 4 root 4.0K Sep 22 12:47 ..
-rw-r--r-- 1 sudo  220 Apr 17  2019 .bash_logout
-rw-r--r-- 1 sudo 3.5K Apr 17  2019 .bashrc
drwxr-xr-x 3 root 4.0K Sep 22 12:49 downloads
-rw-r--r-- 1 sudo  807 Apr 17  2019 .profile
drwxr-xr-x 2 root 4.0K Sep 22 13:15 .spotbit
drwxr-xr-x 5 root 4.0K Sep 22 12:53 spotbit
-rw-r--r-- 1 sudo  169 Sep 22 12:49 .wget-hsts
```

**Comment by watersnake1** [comment]
Hi Shannon,
This was due to the directory that holds the source code changing from /spotbit/source to /spotbit/spotbit. I've changed the README to reflect this change. You should be able to find the logs and source code in /home/spotbit/spotbit
