### ISSUE TITLE
Sqlite3 Database opens in current dir rather than the specified one

### ISSUE THREAD

**Issue by watersnake1** [BlockchainCommons/spotbit#3]
This is a note I am placing here to track the fixing of this issue.

Sqlite3 should connect to a database in an arbitrary location (~/.spotbit/ for example). 

The “~” character to represent the current users home directory isn’t supported as just a string path.

Pathlib has the expanduser() function to interpret a tilde, but it doesn’t seem to be supported by sqlite3. When passed a pathlib object, sqlite3 defaults to the current directory.

Possible solutions
Hard coding the users home directory - bad
Asking for the users name - unnecessary and too much to ask
Obtaining the users home folder from an environment variable ($HOME on Linux I think?) - may be different on Mac 
Exporting a directory path during install and setup then using that as above

**Comment by ChristopherA** [comment]
I know that the both the legacy Mac bash cli supports $HOME as does this year's zsh.

```
% echo $HOME
/Users/christophera
```
