### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by ary2708** [BlockchainCommons/spotbit#56]
I carried on the installation process but I am unable to proceed forward as systemctl spotbit service isn't getting started and is giving the following error:

spotbit.service - Spotbit

Loaded: loaded (/etc/systemd/system/spotbit.service; enabled; vendor preset: enabled)

Active: failed (Result: exit-code) since Sun 2022-04-17 10:02:33 +06; 12s ago

Process: 116403 ExecStart=/usr/local/bin/python3.8 /home/spotbit/spotbit/server.py (code=exited, status=1/FAILURE)

Hint: You are currently not seeing messages from other users and the system.

Users in groups 'adm', 'systemd-journal' can see all messages.

Pass -q to turn off this notice.

-- Logs begin at Sat 2022-04-16 18:01:18 +06, end at Sun 2022-04-17 10:01:28 +06. --

-- No entries --

Can you please help me out.
@watersnake1 @shannona @ChristopherA @javiervargas

**Comment by javiervargas** [comment]
Can you check if there is some related message on /var/log/syslog and share it here, please?

**Comment by ChristopherA** [comment]
There is a new PR #55 that has improvements to Spotbit code that has been submitted for review. You may want to switch to it and see if it solves your problem.

**Comment by ary2708** [comment]
I was able to activate it, but later I am facing a different issue. Creating a separate issue for it.

@javiervargas I am getting the following message for checking the message:
chavan@NitroAN515441b2cf892:~$ cd/var/log
bash: cd/var/log: No such file or directory
chavan@NitroAN515441b2cf892:~$ var/log/syslog
bash: var/log/syslog: No such file or directory
chavan@NitroAN515441b2cf892:~$

Please tell me what am I doing wrong.

**Comment by javiervargas** [comment]
$ more /var/log/syslog
