### ISSUE TITLE
Localhost 5000 not showing anything

### ISSUE THREAD

**Issue by ary2708** [BlockchainCommons/spotbit#57]
I was able to activate status, but still localhost 5000 isn't displaying any content.

chavan@NitroAN515441b2cf892:~/spotbit$ sudo systemctl start spotbit
chavan@NitroAN515441b2cf892:~/spotbit$ sudo systemctl status
● NitroAN515441b2cf892
    State: degraded
     Jobs: 0 queued
   Failed: 1 units
    Since: Sun 2022-04-17 10:51:47 +06; 12h ago
   CGroup: /
           ├─661 bpfilter_umh
           ├─user.slice
           │ └─user-1000.slice
           │   ├─user@1000.service …
           │   │ ├─xdg-desktop-portal-pantheon.service
           │   │ │ └─2644 /usr/lib/x86_64-linux-gnu/xdg-desktop-portal-pantheon
           │   │ ├─gvfs-goa-volume-monitor.service
           │   │ │ └─13604 /usr/libexec/gvfs-goa-volume-monitor
           │   │ ├─app-flatpak-io.elementary.capnet\x2dassist-6967.scope
           │   │ │ ├─6967 bwrap --args 36 io.elementary.capnet-assist
           │   │ │ ├─6988 bwrap --args 36 xdg-dbus-proxy --args=39
           │   │ │ ├─6989 xdg-dbus-proxy --args=39
           │   │ │ ├─6991 bwrap --args 36 io.elementary.capnet-assist
           │   │ │ ├─6992 io.elementary.capnet-assist
           │   │ │ ├─7001 /usr/libexec/webkit2gtk-4.0/WebKitNetworkProcess 5 18
           │   │ │ └─7002 /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 9 20
           │   │ ├─xdg-permission-store.service
           │   │ │ └─2609 /usr/libexec/xdg-permission-store
           │   │ ├─xdg-document-portal.service
           │   │ │ ├─2606 /usr/libexec/xdg-document-portal
           │   │ │ └─2614 fusermount -o rw,nosuid,nodev,fsname=portal,auto_unmount,subtype=portal -- /run/user/1000/doc
           │   │ ├─zeitgeist.service
           │   │ │ └─2876 /usr/bin/zeitgeist-daemon
           │   │ ├─xdg-desktop-portal.service
           │   │ │ ├─2602 /usr/libexec/xdg-desktop-portal
           │   │ │ ├─2630 sh -c /usr/lib/x86_64-linux-gnu/libproxy/0.4.15/pxgsettings org.gnome.system.proxy org.gnome.system.proxy.http org.gnome.system.proxy.https org.g>
           │   │ │ └─2631 /usr/lib/x86_64-linux-gnu/libproxy/0.4.15/pxgsettings org.gnome.system.proxy org.gnome.system.proxy.http org.gnome.system.proxy.https org.gnome.s>
           │   │ ├─evolution-calendar-factory.service
           │   │ │ └─2797 /usr/libexec/evolution-calendar-factory
           │   │ ├─pulseaudio.service
           │   │ │ └─2303 /usr/bin/pulseaudio --daemonize=no --log-target=journal
           │   │ ├─gvfs-daemon.service
           │   │ │ ├─ 2319 /usr/libexec/gvfsd
           │   │ │ ├─ 2324 /usr/libexec/gvfsd-fuse /run/user/1000/gvfs -f -o big_writes
           │   │ │ ├─ 8333 /usr/libexec/gvfsd-trash --spawner :1.3 /org/gtk/gvfs/exec_spaw/0
           │   │ │ ├─ 8373 /usr/libexec/gvfsd-http --spawner :1.3 /org/gtk/gvfs/exec_spaw/1
           │   │ │ └─13666 /usr/libexec/gvfsd-recent --spawner :1.3 /org/gtk/gvfs/exec_spaw/2
           │   │ ├─io.elementary.files.xdg-desktop-portal.service

chavan@NitroAN515441b2cf892:~/spotbit$ systemctl reset-failed
Failed to execute operation: Connection timed out
chavan@NitroAN515441b2cf892:~/spotbit$ systemctl reset-failed
chavan@NitroAN515441b2cf892:~/spotbit$ sudo systemctl status
● NitroAN515441b2cf892
    State: running
     Jobs: 0 queued
   Failed: 0 units
    Since: Sun 2022-04-17 10:51:47 +06; 12h ago
   CGroup: /
           ├─661 bpfilter_umh
           ├─user.slice
           │ └─user-1000.slice
           │   ├─user@1000.service …
           │   │ ├─xdg-desktop-portal-pantheon.service
           │   │ │ └─2644 /usr/lib/x86_64-linux-gnu/xdg-desktop-portal-pantheon
           │   │ ├─gvfs-goa-volume-monitor.service
           │   │ │ └─13604 /usr/libexec/gvfs-goa-volume-monitor
           │   │ ├─app-flatpak-io.elementary.capnet\x2dassist-6967.scope
           │   │ │ ├─6967 bwrap --args 36 io.elementary.capnet-assist
           │   │ │ ├─6988 bwrap --args 36 xdg-dbus-proxy --args=39
           │   │ │ ├─6989 xdg-dbus-proxy --args=39
           │   │ │ ├─6991 bwrap --args 36 io.elementary.capnet-assist
           │   │ │ ├─6992 io.elementary.capnet-assist
           │   │ │ ├─7001 /usr/libexec/webkit2gtk-4.0/WebKitNetworkProcess 5 18
           │   │ │ └─7002 /usr/libexec/webkit2gtk-4.0/WebKitWebProcess 9 20
           │   │ ├─xdg-permission-store.service
           │   │ │ └─2609 /usr/libexec/xdg-permission-store
           │   │ ├─xdg-document-portal.service
           │   │ │ ├─2606 /usr/libexec/xdg-document-portal
           │   │ │ └─2614 fusermount -o rw,nosuid,nodev,fsname=portal,auto_unmount,subtype=portal -- /run/user/1000/doc
           │   │ ├─zeitgeist.service
           │   │ │ └─2876 /usr/bin/zeitgeist-daemon
           │   │ ├─xdg-desktop-portal.service
           │   │ │ ├─2602 /usr/libexec/xdg-desktop-portal
           │   │ │ ├─2630 sh -c /usr/lib/x86_64-linux-gnu/libproxy/0.4.15/pxgsettings org.gnome.system.proxy org.gnome.system.proxy.http org.gnome.system.proxy.https org.g>
           │   │ │ └─2631 /usr/lib/x86_64-linux-gnu/libproxy/0.4.15/pxgsettings org.gnome.system.proxy org.gnome.system.proxy.http org.gnome.system.proxy.https org.gnome.s>
           │   │ ├─evolution-calendar-factory.service
           │   │ │ └─2797 /usr/libexec/evolution-calendar-factory
           │   │ ├─pulseaudio.service
           │   │ │ └─2303 /usr/bin/pulseaudio --daemonize=no --log-target=journal
           │   │ ├─gvfs-daemon.service
           │   │ │ ├─ 2319 /usr/libexec/gvfsd
           │   │ │ ├─ 2324 /usr/libexec/gvfsd-fuse /run/user/1000/gvfs -f -o big_writes
           │   │ │ ├─ 8333 /usr/libexec/gvfsd-trash --spawner :1.3 /org/gtk/gvfs/exec_spaw/0
           │   │ │ ├─ 8373 /usr/libexec/gvfsd-http --spawner :1.3 /org/gtk/gvfs/exec_spaw/1
           │   │ │ └─13666 /usr/libexec/gvfsd-recent --spawner :1.3 /org/gtk/gvfs/exec_spaw/2
           │   │ ├─io.elementary.files.xdg-desktop-portal.service

I have been trying to do this since 2-3 days but nothing yet.
Please solve this issue.

**Comment by nochiel** [comment]
Please could you share your `spotbit.log` file? 

It's in `/home/spotbit/.spotbit/spotbit.log`.

**Comment by nochiel** [comment]
If you are using https://github.com/BlockchainCommons/spotbit/pull/55 please do not use the `installSpotbit.sh` because it has not yet been updated.

Instead, run `python app..py`

**Comment by ary2708** [comment]
This is what is written

```
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db
db opened in /home/spotbit/.spotbit/sb.db

```
@nochiel also i am not using #55 as of now. What am i supposed to run then?

**Comment by nochiel** [comment]
What output do you get from `journalctl -u spotbit`?

When running from `master` the installation script should work as is.

**Comment by ChristopherA** [comment]
@ary2708 If you are using the wonderful `gh` tool from Github, you can merge in PR #57 with `gh pr checkout 55` and you will be using that more recent version of Spotbit.

**Comment by nochiel** [comment]
Fixed in master.
