### ISSUE TITLE
Hi from the Bitcoin Development Kit team

### ISSUE THREAD

**Issue by thunderbiscuit** [BlockchainCommons/spotbit#75]
Hey! Not an issue per se, but I wanted to say I just realized you're using bdkpython!

We want to make sure we support the projects who are using the bitcoin development kit, and would love to hear your thoughts on how the library has worked out for you so far.

The bulk of the development and the discussion on the API surface for the language bindings (Python, JVM/Java/Kotlin, Android, and Swift) is happening on the [bdk-ffi repository](https://github.com/bitcoindevkit/bdk-ffi) and on the #ffi-bindings channel of our [Discord server](https://discord.gg/Rd8nmDrn). Feel free to hop in anytime, and let us know about your use case for the library and/or if you'd like new APIs from the bitcoindevkit to be exposed on the Python side of things.

We also have language bindings dev calls every two weeks; the agendas are [here](https://hackmd.io/@thunderbiscuit/devcalls/%2FPPbAp6FRSQ6eaT81gigr5A).

Cheers!

**Comment by notmandatory** [comment]
Captured from comment in beancounter.py, should we create `bdk-python` or issues here in `spotbit` for these?

 - [ ] generate a descriptor from an extended key.
 - [ ] test if an address belongs to a HDkey
 - [ ] query Esplora or Electrum/Electrs using an agnostic API.
 - [ ] load utxo transaction history

**Comment by thunderbiscuit** [comment]
Reach out if you ever want to discuss anything related to our library or our bindings!
