### ISSUE TITLE
installing requirements returns errors about sqlite

### ISSUE THREAD

**Issue by Fonta1n3** [BlockchainCommons/spotbit#9]
Install python3.8 on debian 10
`cd spotbit`
`source spotbit_venv/bin/activate`
`pip install -r requirements.txt`

`ERROR: Could not find a version that satisfies the requirement sqlite (from -r requirements.txt (line 4)) (from versions: none)`

**Comment by Fonta1n3** [comment]
im a python newb... seems like this is only bc sqlite comes already installed by default >python2.5 maybe remove it from the `requirements.txt`?

**Comment by watersnake1** [comment]
Yes I think you are correct about python and SQLite. As soon as I’m in front of a computer I can make that change, thanks!
